POST http://localhost:3000/create-users/
Content-Type: application/json

{
    "email":"bhaskar@gmail.com",
    "password": "babu"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "email":"bhaskar@gmail.com",
    "password": "babu"
}

###